improve hints
Zhouzi/name-the-gwent-card pull request #31
Opened 2020-10-14 16:37 UTC by RinZero

I implemented the changes suggested in Issue #21

2020-10-15 15:42 UTC, Zhouzi requested changes
Awesome, thank you so much for helping with that 👍

I made a few comments, please do not hesitate if you need help with anything. I would be happy to help 😉

2020-10-15 15:42 UTC, Zhouzi commented on src/app/components/Game/CardHints.tsx
> +                      cardGroup: card.type,
Could you rename `cardGroup` to `cardType`? It needs to be updated in the type declaration and `HINTS` array as well (in this file).

The messages also have to be updated (updating the `hintCardGroup` key to `hintCardType`). Ideally, the type should be translated as well.

Here's for the english translation:

```diff
- hintCardGroup: "This is a {cardGroup} card",
+ hintCardType: "This is a {type, select, unit {unit} special {special} artifact {artifact}} card",
```

And french:

```diff
- hintCardGroup: "C'est une carte {cardGroup}",
+ hintCardType: "C'est une carte {type, select, unit {unité} special {spéciale} artifact {artefact}}",
```

2020-10-15 15:42 UTC, Zhouzi commented on src/app/i18n/en/messages.ts
> +  remaining: " ({remainCount} left)"
Instead of adding a new key, could you update the current `hint`? As so:

```diff
- hint: "Hint",
+ hint: "Hint ({remainCount} left)",
```

2020-10-15 15:42 UTC, Zhouzi commented on src/app/i18n/fr/messages.ts
> +  remaining: " ({remainCount} rester)"
The french translation would be `({remainCount} restants)`.

2020-10-16 12:46 UTC, RinZero commented
Thanl you for the detailed feedback, especially the translations helped me a lot, because my french is terrible. 😉

2020-10-16 13:13 UTC, Zhouzi commented
@all-contributors please add @RinZero for code

2020-10-16 13:13 UTC, Zhouzi approved these changes
🙌

2020-10-16 13:14 UTC, merged